### ISSUE TITLE
How to download pdf into user's computer

### ISSUE THREAD

**Issue by Kistlak** [pdfshift/pdfshift-php#4]
I use Laravel in this case. I have implemented all the things according to the documentation. After that, I was able to save pdf into the project directory. But , I want to download pdf to the user's computer when someone clicks the download link. Then how can I do this ??

The method that I used.

```
PDFShift::setApiKey('120d8e8a86d2....................');
PDFShift::convertTo('https://www.example.com', null, 'result.pdf');
```

**Comment by cnicodeme** [comment]
Hi,

In that case, you should output the data returned by PDFShift's server by first setting the headers to be of content-type "Application/pdf", like this:

```php
    header($_SERVER["SERVER_PROTOCOL"] . " 200 OK");
    header("Cache-Control: public"); // needed for internet explorer
    header("Content-Type: application/pdf");
    header("Content-Transfer-Encoding: Binary");
    header("Content-Length:".strlen($pdf_api_response));
    header("Content-Disposition: attachment; filename=report.pdf");
    echo $pdf_api_response;
```

Hope that make sense. For further details, please reach out the support team at support@pdfshift.io.
