### ISSUE TITLE
Arabic font

### ISSUE THREAD

**Issue by greatsami** [pdfshift/pdfshift-php#7]
Can we change the font family for Arabic Characters as (Arial or another compatible Arabic font)?

**Comment by cnicodeme** [comment]
The PDF format is very restricted in term of fonts and limits the fonts to a very specific list. You can, of course, embed any other font as "extra" and use them. It works great for any languages.

When converting a document from HTML to PDF, if any custom font is used, PDFShift will add the fonts it was able to find, and they will be rendered in the PDF.

If you use "font-family" or web fonts in your HTML page, it should work flawlessly.

If you have any issues, please open a ticket on our support at support@pdfshift.io.

Thanks.
